test: Fix tests for `.tool-versions`
Also add new `.tool-versions` function that just parses it

diff --git a/bake b/bake
--- a/bake
+++ b/bake
@@ -91,25 +91,59 @@ bake.assert_cmd() {
 	fi
 }
 
+# @description Determine if a flag was passed as an argument
+# @arg $1 string Flag name to test for
+# @arg $@ string Rest of the arguments to search through
+bake.has_flag() {
+	local flag_name="$1"
+
+	if [ -z "$flag_name" ]; then
+		bake.die "Argument must not be empty"
+	fi
+	if ! shift; then
+		bake.die 'Failed to shift'
+	fi
+
+	local arg=
+	for arg; do
+		if [ "$arg" = "$flag_name" ]; then
+			return 0
+		fi
+	done; unset -v arg
+
+	return 1
+}
+
 # @description Change the behavior of Bake. See [guide.md](./docs/guide.md) for details
 # @arg $1 string Name of config property to change
 # @arg $2 string New value of config property
 bake.cfg() {
-	local cfg=$1
-	local value=$2
+	local cfg="$1"
+	local value="$2"
 
 	case $cfg in
 	stacktrace)
 		case $value in
-			yes|no) __bake_cfg_stacktrace=$value ;;
-			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'yes' or 'no'" ;;
+			yes) __bake_internal_warn "Passing either 'yes' or 'no' as a value for 'bake.cfg stacktrace' is deprecated. Instead, use either 'on' or 'off'"; __bake_cfg_stacktrace='on' ;;
+			no) __bake_internal_warn "Passing either 'yes' or 'no' as a value for 'bake.cfg stacktrace' is deprecated. Instead, use either 'on' or 'off'"; __bake_cfg_stacktrace='off' ;;
+			on|off) __bake_cfg_stacktrace=$value ;;
+			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'on' or 'off'" ;;
 		esac
 		;;
 	pedantic-task-cd)
 		case $value in
-			yes) trap '__bake_trap_debug' 'DEBUG' ;;
-			no) trap - 'DEBUG' ;;
-			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'yes' or 'no'" ;;
+			yes) __bake_internal_warn "Passing either 'yes' or 'no' as a value for 'bake.cfg pedantic-task-cd' is deprecated. Instead, use either 'on' or 'off'"; trap '__bake_trap_debug' 'DEBUG' ;;
+			no) __bake_internal_warn "Passing either 'yes' or 'no' as a value for 'bake.cfg pedantic-task-cd' is deprecated. Instead, use either 'on' or 'off'"; trap - 'DEBUG' ;;
+			on) trap '__bake_trap_debug' 'DEBUG' ;;
+			off) trap - 'DEBUG' ;;
+			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'on' or 'off'" ;;
+		esac
+		;;
+	big-print)
+		case $value in
+			yes|no) __bake_internal_warn "Passing either 'yes' or 'no' as a value for 'bake.cfg big-print' is deprecated. Instead, use either 'on' or 'off'" ;;
+			on|off) ;;
+			*) __bake_internal_die2 "Config property '$cfg' accepts only either 'on' or 'off'" ;;
 		esac
 		;;
 	*)
@@ -121,7 +155,7 @@ bake.cfg() {
 # @description Prints stacktrace
 # @internal
 __bake_print_stacktrace() {
-	if [ "$__bake_cfg_stacktrace" = 'yes' ]; then
+	if [ "$__bake_cfg_stacktrace" = 'on' ]; then
 		if __bake_is_color; then
 			printf '\033[4m%s\033[0m\n' 'Stacktrace:'
 		else
@@ -167,11 +201,17 @@ __bake_trap_debug() {
 # @exitcode 1 if should not print color
 # @internal
 __bake_is_color() {
-	if [[ -v NO_COLOR || $TERM == dumb ]]; then
+	local fd="1"
+
+	if [[ ${NO_COLOR+x} || "$TERM" = 'dumb' ]]; then
 		return 1
-	else
+	fi
+
+	if [ -t "$fd" ]; then
 		return 0
 	fi
+
+	return 1
 }
 
 # @description Calls `__bake_internal_error` and terminates with code 1
@@ -234,11 +274,22 @@ __bake_print_tasks() {
 	local str=
 
 	# shellcheck disable=SC1007,SC2034
-	local regex="^(([[:space:]]*function[[:space:]]*)?task\.(.*?)\(\)).*"
+	local regex="^([[:space:]]*function[[:space:]]*)?task\.(.*?)\(\)[[:space:]]*\{[[:space:]]*(#[[:space:]]*(.*))?"
 	local line=
 	while IFS= read -r line || [ -n "$line" ]; do
 		if [[ "$line" =~ $regex ]]; then
-			str+="  -> ${BASH_REMATCH[3]}"$'\n'
+			str+="  -> ${BASH_REMATCH[2]}"
+
+			local task_comment=${BASH_REMATCH[4]}
+			if [ -n "$task_comment" ]; then
+				if __bake_is_color; then
+					str+=$' \033[3m'"($task_comment)"$'\033[0m'
+				else
+					str+=" ($task_comment)"
+				fi
+			fi
+
+			str+=$'\n'
 		fi
 	done < "$BAKE_FILE"; unset -v line
 
@@ -259,13 +310,21 @@ __bake_print_tasks() {
 __bake_print_big() {
 	local print_text="$1"
 
+	if [ "$__bake_cfg_big_print" = 'off' ]; then
+		return
+	fi
+
 	# shellcheck disable=SC1007
 	local _stty_height= _stty_width=
 	read -r _stty_height _stty_width < <(
-		if command -v stty &>/dev/null; then
+		if stty size &>/dev/null; then
 			stty size
 		else
-			printf '%s\n' '20 80'
+			if [ -n "$COLUMNS" ]; then
+				printf '%s\n' "20 $COLUMNS"
+			else
+				printf '%s\n' '20 80'
+			fi
 		fi
 	)
 
@@ -288,7 +347,6 @@ __bake_parse_args() {
 	unset REPLY; REPLY=
 	local -i total_shifts=0
 
-	# FIXME: bug for when passing -v to child task argument
 	local __bake_arg=
 	for arg; do case $arg in
 	-f)
@@ -309,14 +367,19 @@ __bake_parse_args() {
 		fi
 		;;
 	-v)
-		local bake_version='1.7.0'
+		local bake_version='1.9.0'
 		printf '%s\n' "Version: $bake_version"
+		exit 0
 		;;
 	-h)
 		local flag_help='yes'
 		if ! shift; then
 			__bake_internal_die 'Failed to shift'
 		fi
+		;;
+	*)
+		break
+		;;
 	esac done
 
 	if [ -n "$BAKE_FILE" ]; then
@@ -359,16 +422,20 @@ __bake_parse_args() {
 # @description Main function
 # @internal
 __bake_main() {
-	__bake_cfg_stacktrace='no'
+	__bake_cfg_stacktrace='off'
+	__bake_cfg_big_print='on'
 
+	# Environment boilerplate
 	set -ETeo pipefail
 	shopt -s dotglob extglob globasciiranges globstar lastpipe shift_verbose
 	export LANG='C' LC_CTYPE='C' LC_NUMERIC='C' LC_TIME='C' LC_COLLATE='C' \
 		LC_MONETARY='C' LC_MESSAGES='C' LC_PAPER='C' LC_NAME='C' LC_ADDRESS='C' \
 		LC_TELEPHONE='C' LC_MEASUREMENT='C' LC_IDENTIFICATION='C' LC_ALL='C'
 	trap '__bake_trap_err' 'ERR'
-	bake.cfg pedantic-task-cd 'no'
+	trap ':' 'INT' # Ensure Ctrl-C ends up printing <- ERROR ==== etc.
+	bake.cfg pedantic-task-cd 'off'
 
+	# Parse arguments
 	# Set `BAKE_{ROOT,FILE}`
 	BAKE_ROOT=; BAKE_FILE=
 	__bake_parse_args "$@"
@@ -376,6 +443,7 @@ __bake_main() {
 		__bake_internal_die 'Failed to shift'
 	fi
 
+	# Set variables à la Make
 	# shellcheck disable=SC1007
 	local __bake_key= __bake_value=
 	local __bake_arg=
@@ -393,8 +461,8 @@ __bake_main() {
 			;;
 		*) break
 	esac done; unset -v __bake_arg
-	# Note: Don't unset '__bake_variable' or none of the variables will stay set
 	unset -v __bake_key __bake_value
+	unset -vn __bake_variable
 
 	local __bake_task="$1"
 	if [ -z "$__bake_task" ]; then
@@ -414,6 +482,21 @@ __bake_main() {
 	__bake_task= source "$BAKE_FILE"
 
 	if declare -f task."$__bake_task" >/dev/null 2>&1; then
+		local line=
+		local shouldTestNextLine='no'
+		while IFS= read -r line; do
+			if [ "$shouldTestNextLine" = 'yes' ]; then
+				if [[ $line == *'bake.cfg'*big-print*@(no|off)* ]]; then
+					__bake_cfg_big_print='off'
+				fi
+				shouldTestNextLine='no'
+			fi
+
+			if [[ $line == @(task."$__bake_task"|init)*'('*')'*'{' ]]; then
+				shouldTestNextLine='yes'
+			fi
+		done < "$BAKE_FILE"; unset -v line shouldTestNextLine
+
 		__bake_print_big "-> RUNNING TASK '$__bake_task'"
 		if declare -f init >/dev/null 2>&1; then
 			init "$__bake_task"
